-- AlterTable
ALTER TABLE "Order" ADD COLUMN     "localShippingPrice" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "shippingPrice" DOUBLE PRECISION NOT NULL DEFAULT 0,
ALTER COLUMN "price" SET DEFAULT 0;
